version: "3.8"
services:
    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        networks:
          - rabbit
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword123
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'

networks:
  rabbit:
    driver: bridge